### ISSUE TITLE
Produce a meta output file with the complete program description

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/QGL#44]
i.e. we want to have:
- [ ] a dictionary from instruments to their compiled sequence files
- [ ] some equivalent information for receivers/digitizers
    - [ ] including some representation of the difference between a segment and a capture event (i.e. if there are multiple `MEAS`s in a sequence
- [ ] label information for swept parameters

**Comment by caryan** [comment]
For the receiver section we also need some way to describe variable number of captures per segment. It might also be the place to think about what an experiment debug record would look like.

**Comment by caryan** [comment]
Some initial work in #49 to save the pulse sequence string

**Comment by blakejohnson** [comment]
`ReceiverChannel`s add in #91.
